version: "3.8"

services:

  nginx:

    image: library/nginx:stable

    ports:
      - 80:80

    links:
      - php-fpm

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/php-error.log:/var/log/nginx/php-error.log

  php-fpm:

    image: library/php:fpm

    ports:
    - 9000:9000

    volumes:
    - ./application:/var/www/application



